import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({children,}: Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <header style={{background: "#f5f5f5"}}>
          <p>this is header</p>
      </header>
        <main style={{ padding: "24px" }}>
          {children}  {/* 여기에 page.tsx 내용이 들어감 */}
        </main>
      <footer style={{background: "#f5f5f5"}}>
          <p>© 2025 My App. All rights reserved.</p>
      </footer>
      </body>
    </html>
  );
}
